# Global configuration for Prometheus monitoring system
global:
  scrape_interval: 15s      # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules
  scrape_timeout: 10s       # How long until a scrape times out

# Rule files - this is where alerting rules would be referenced
rule_files: []

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape configurations - defines the targets Prometheus will monitor
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Health Advisor backend metrics
  - job_name: 'health-advisor-backend'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:5000']
        labels:
          service: 'backend'

  # MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          service: 'mongodb'

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'

  # Mobile application metrics
  - job_name: 'mobile-metrics'
    metrics_path: '/api/mobile-metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['backend:5000']
        labels:
          service: 'mobile-app'

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention_time: 15d