version: "3.8"  # docker-compose version: 3.8

services:
  backend:
    build:
      context: ../src/backend
      dockerfile: Dockerfile
      target: base
    container_name: health-advisor-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9229:9229" # Expose debug port
    environment:
      NODE_ENV: development
      PORT: 5000
      API_PREFIX: /api
      MONGODB_URI: mongodb://mongodb:27017/health-advisor-dev
      JWT_SECRET: dev-jwt-secret
      JWT_EXPIRATION: 1d
      REFRESH_TOKEN_EXPIRATION: 7d
      LLM_PROVIDER_API_KEY: ${LLM_PROVIDER_API_KEY}
      LLM_PROVIDER_URL: https://api.openai.com/v1
      LLM_MODEL: gpt-4
      CORS_ORIGIN: "*"
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 1000
      LOG_LEVEL: debug
    volumes:
      - ../src/backend:/app # Mount source code for hot reloading
      - node_modules_backend:/app/node_modules # Persist node_modules
    command: npm run dev # Run development server
    depends_on:
      - mongodb
    networks:
      - health_advisor_network

  web:
    build:
      context: ../src/web
      dockerfile: Dockerfile
    container_name: health-advisor-web-dev
    restart: unless-stopped
    ports:
      - "8081:8081" # React Native port
      - "19000:19000" # Expo port
      - "19001:19001" # Expo port
      - "19002:19002" # Expo port
    environment:
      NODE_ENV: development
      API_URL: http://backend:5000/api
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0 # Allow Expo DevTools to be accessible from outside the container
      REACT_NATIVE_PACKAGER_HOSTNAME: 0.0.0.0 # Configure React Native packager to be accessible from outside the container
    volumes:
      - ../src/web:/app # Mount source code for hot reloading
      - node_modules_web:/app/node_modules # Persist node_modules
    command: npm start # Run React Native development server
    depends_on:
      - backend
    networks:
      - health_advisor_network

  mongodb:
    image: mongo:6.0 # mongodb version: 6.0
    container_name: health-advisor-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data
    networks:
      - health_advisor_network
    command: mongod --logpath=/dev/null

volumes:
  mongodb_data:
    driver: local
  node_modules_backend:
    driver: local
  node_modules_web:
    driver: local

networks:
  health_advisor_network:
    driver: bridge